### PR TITLE
Enable compatibility with redux-observable@1.x, redux@4.x and rxjs@6.x

### PR DESCRIPTION
**Pull request by jdachtera**
Hi @BerkeleyTrue,

This pr enables compatibility with redux-observable@1.x, redux@4.x and rxjs@6.x. (without the need for the rxjs5 compat layer).

Let me know if you need anything to get this merged.

Cheers,
Jascha

### CODE REVIEW

**Comment by jdachtera** [comment]
@BerkeleyTrue, any chance to get this merged?

**Comment by BentoumiTech** [comment]
@jdachtera Probably some changes would be also needed in the `docs/api/README.md` as `createEpicMiddleware` signature changed.

**Comment by jdachtera** [comment]
@Neophy7e, thanks! I'll add that as soon as possible.

**Comment by jdachtera** [comment]
@NeoPhy7e, @BerkeleyTrue, added the the documentation changes.
Let me know what you think!

**Comment by BentoumiTech** [comment]
@jdachtera @BerkeleyTrue I don't know if you were aware but there is currently two PR's in the `redux-observable` repo that aims to implement SSR directly in the library. Maybe your experience `redux-observable` and SSR could help out there.

- https://github.com/redux-observable/redux-observable/pull/539
- https://github.com/redux-observable/redux-observable/pull/412

**Comment by jdachtera** [comment]
@Neophy7e thanks for pointing this out. My impression of these discussions is that it doesn't seem to be easy to align on the technical implementation. Maybe then it's better to keep it as a separate library for now.

Also as a builtin feature it might increase the bundle size on the client side event though it would only be needed on the server.

Since there has been no activity by the maintainer I've published this under a new namespace for now so everyone can easily use it: 
https://www.npmjs.com/package/@jdachtera/react-redux-epic

Cheers!

**Comment by BentoumiTech** [comment]
@jdachtera Thank you for making it available through npm.

**Pull request closed without merging**
